"""Add quiz attempt models

Revision ID: 282dc019a097
Revises: 2eaaf3e7166e
Create Date: 2025-08-23 21:09:08.004945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282dc019a097'
down_revision: Union[str, None] = '2eaaf3e7166e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
